### PR TITLE
Fix csp error for style-src (breaking dark mode)

### LINKED ISSUE #170: Reactions stuck in dark mode
image

### PR DESCRIPTION
**Pull request by bravo-kernel**
Closes #170

### CODE REVIEW

**Comment by bravo-kernel** [comment]
@fflaten this solves the issue for me on Chrome, same for you?

Also, I lost the mention of the angle brackets issue. Did the new module solve that?

**Comment by fflaten** [comment]
Works in preview :)

**Comment by bravo-kernel** [comment]
Woohoo, let's go 💃

> Still wondering what you were doing on my blog though 😂

**Comment by fflaten** [comment]
> Woohoo, let's go 💃
> 
> > Still wondering what you were doing on my blog though 😂

Checking if you were associated with codesandbox because of the shameless plug 😄

**Comment by bravo-kernel** [comment]
No I am not, I just think it could be super useful for support.

Imagine “why does this not sort correctly?” in a live box instead of people posting code. And then just show the working answer. 

Sent from my Mobile Device

**Comment by fflaten** [comment]
I absolutely agree. 👍 
Astro, which I use to build my website, require a repro like that in their [issue templates](https://github.com/withastro/astro/issues/new?assignees=&labels=&template=---01-bug-report.yml) and with a good template to begin with, it's so easy.

**Pull request merged**
